### ISSUE TITLE
LeavePacketBySocketTest returns a System.Net.SocketException when run with other tests

### ISSUE THREAD

**Issue by Insane96** [aiv01/brawler-server#13]
LeavePacketBySocketTest returns
`System.Net.SocketException - Only one usage of each socket address (protocol/network address/port) is normally permitted`
when Run with other tests.
The test doesn't fail if the test is run alone.

**Comment by luxkun** [comment]
I think that we can fix this by making sure that every test that create a binded server also uses an unique test port.
